name: Ingest ProQuest ETDs

on:
  workflow_dispatch:
jobs:
  run:
    timeout-minutes: 15
    runs-on: self-hosted
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - id: 'auth_rw'
        name: 'Authenticate to Google Cloud (read+write)'
        uses: 'google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f' # v2
        with:
          workload_identity_provider: ${{ secrets.WORKBENCH_GCLOUD_OIDC_POOL }}
          service_account: ${{ secrets.WORKBENCH_GSA }}
          token_format: 'access_token'
          access_token_scopes: "https://www.googleapis.com/auth/spreadsheets,https://www.googleapis.com/auth/drive"

      - name: Run
        run: ./scripts/etds.sh
        env:
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
